services:
  db:
    image: mysql:8
    restart: always
    environment:
      MYSQL_DATABASE: ross
      MYSQL_USER: user
      MYSQL_PASSWORD: pass
      MYSQL_ROOT_PASSWORD: password
    volumes:
      - db_data:/var/lib/mysql

  wordpress:
    image: wordpress:latest
    restart: always
    ports:
      - "8000:80"
    environment:
      WORDPRESS_DB_HOST: db:3306
      WORDPRESS_DB_USER: user
      WORDPRESS_DB_PASSWORD: pass
      WORDPRESS_DB_NAME: ross
      WP_ENV: development
    volumes:
      - wordpress_data:/var/www/html
      - ./theme:/var/www/html/wp-content/themes/ross 
      - ./blocks/build:/var/www/html/wp-content/plugins/ross/build
      - ./blocks/ross.php:/var/www/html/wp-content/plugins/ross/ross.php

volumes:
  wordpress_data:
  db_data:
